name: Build and push pgtuned images

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        include:
          - postgres_version: 15
            tags: esgn/pgtuned:15, esgn/pgtuned:latest
          - postgres_version: 15
            postgis_version: 3
            tags: esgn/pgtuned:15-3, esgn/pgtuned:postgis-latest
          - postgres_version: 14
            tags: esgn/pgtuned:14
          - postgres_version: 14
            postgis_version: 3
            tags: esgn/pgtuned:14-3
          - postgres_version: 13
            tags: esgn/pgtuned:13
          - postgres_version: 13
            postgis_version: 3
            tags: esgn/pgtuned:13-3
          - postgres_version: 12
            tags: esgn/pgtuned:12
          - postgres_version: 12
            postgis_version: 3
            tags: esgn/pgtuned:12-3
          - postgres_version: 11-bullseye
            tags: esgn/pgtuned:11
          - postgres_version: 11-bullseye
            postgis_version: 3
            tags: esgn/pgtuned:11-3
          - postgres_version: 11
            postgis_version: 2.5
            tags: esgn/pgtuned:11-2.5
          - postgres_version: 10-bullseye
            tags: esgn/pgtuned:10
          - postgres_version: 10-bullseye
            postgis_version: 3
            tags: esgn/pgtuned:10-3
          - postgres_version: 10
            postgis_version: 2.5
            tags: esgn/pgtuned:10-2.5
          - postgres_version: 10
            postgis_version: 2.4
            tags: esgn/pgtuned:10-2.4
          - postgres_version: 9.6-bullseye
            tags: esgn/pgtuned:9.6
          - postgres_version: 9.6-bullseye
            postgis_version: 3
            tags: esgn/pgtuned:9.6-3
          - postgres_version: 9.6
            postgis_version: 2.5
            tags: esgn/pgtuned:9.6-2.5
          - postgres_version: 9.6
            postgis_version: 2.4
            tags: esgn/pgtuned:9.6-2.4
          - postgres_version: 9.6
            postgis_version: 2.3
            tags: esgn/pgtuned:9.6-2.3
          - postgres_version: 9.5
            tags: esgn/pgtuned:9.5
          - postgres_version: 9.5
            postgis_version: 3
            tags: esgn/pgtuned:9.5-3
          - postgres_version: 9.5
            postgis_version: 2.5
            tags: esgn/pgtuned:9.5-2.5
          - postgres_version: 9.5
            postgis_version: 2.4
            tags: esgn/pgtuned:9.5-24
          - postgres_version: 9.5
            postgis_version: 2.3
            tags: esgn/pgtuned:9.5-2.3

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            POSTGRES_VERSION=${{ matrix.postgres_version }}
            POSTGIS_VERSION=${{ matrix.postgis_version }}
          tags: ${{ matrix.tags }}
